interface  estabilidadDesplazamiento{
   objetivoEsp1: number,
   objetivoEsp2: number,
   objetivoEsp3: number,
   objetivoEsp4: number,
   objetivoEsp5: number,
   objetivoEsp6: number,
   objetivoEsp7: number,
   objetivoEsp8: number,
   objetivoEsp9: number,
   objetivoEsp10: number,
   objetivoEsp11: number,
   objetivoEsp12: number,
   objetivoEsp13: number,
   objetivoEsp14: number,
   objetivoEsp15: number,
   objetivoEsp16: number,
   objetivoEsp17: number,
   objetivoEsp18: number,
   objetivoEsp19: number,
   objetivoEsp20: number,
   objetivoEsp21: number,
   objetivoEsp22: number,
   objetivoEsp23: number,
   objetivoEsp24: number,
   objetivoEsp25: number,
   objetivoEsp26: number,
   objetivoEsp27: number,
   objetivoEsp28: number,
   objetivoEsp29: number,
   objetivoEsp30: number,
   objetivoEsp31: number,
   objetivoEsp32: number,
   objetivoEsp33: number,
   objetivoEsp34: number,
   objetivoEsp35: number,
   objetivoEsp36: number,
   objetivoEsp37: number
  
}
interface  coordinacionDinamica{
   objetivoEsp1: number,
   objetivoEsp2: number,
   objetivoEsp3: number,
   objetivoEsp4: number,
   objetivoEsp5: number,
   objetivoEsp6: number,
   objetivoEsp7: number,
   objetivoEsp8: number,
   objetivoEsp9: number,
   objetivoEsp10: number,
   objetivoEsp11: number,
   objetivoEsp12: number,
   objetivoEsp13: number,
   objetivoEsp14: number,
   objetivoEsp15: number,
   objetivoEsp16: number,
   objetivoEsp17: number,
   objetivoEsp18: number,
   objetivoEsp19: number,
   objetivoEsp20: number,
   objetivoEsp21: number,
   objetivoEsp22: number,
   objetivoEsp23: number,
   objetivoEsp24: number,
   objetivoEsp25: number,
   objetivoEsp26: number,
   objetivoEsp27: number,
   objetivoEsp28: number
  
}
interface  conductasPsicomotoras{
   objetivoEsp1: number,
   objetivoEsp2: number,
   objetivoEsp3: number,
   objetivoEsp4: number,
   objetivoEsp5: number,
   objetivoEsp6: number,
   objetivoEsp7: number,
   objetivoEsp8: number,
   objetivoEsp9: number,
   objetivoEsp10: number,
   objetivoEsp11: number,
   objetivoEsp12: number,
   objetivoEsp13: number,
   objetivoEsp14: number,
   objetivoEsp15: number,
   objetivoEsp16: number,
   objetivoEsp17: number,
   objetivoEsp18: number,
   objetivoEsp19: number,
   objetivoEsp20: number,
   objetivoEsp21: number,
   objetivoEsp22: number,
   objetivoEsp23: number,
   objetivoEsp24: number,
   objetivoEsp25: number,
   objetivoEsp26: number,
   objetivoEsp27: number,
   objetivoEsp28: number,
   objetivoEsp29: number,
   objetivoEsp30: number,
   objetivoEsp31: number,
   objetivoEsp32: number,
   objetivoEsp33: number,
   objetivoEsp34: number,
   objetivoEsp35: number,
   objetivoEsp36: number,
   objetivoEsp37: number,
   objetivoEsp38: number,
   objetivoEsp39: number
  
}
interface  alineacionPostural{
   objetivoEsp1: number,
   objetivoEsp2: number,
   objetivoEsp3: number,
   objetivoEsp4: number,
   objetivoEsp5: number,
   objetivoEsp6: number,
   objetivoEsp7: number,
   objetivoEsp8: number,
   objetivoEsp9: number,
   objetivoEsp10: number,
   objetivoEsp11: number,
   objetivoEsp12: number,
   objetivoEsp13: number,
   objetivoEsp14: number,
   objetivoEsp15: number,
   objetivoEsp16: number,
   objetivoEsp17: number,
   objetivoEsp18: number,
   objetivoEsp19: number,
   objetivoEsp20: number,
   objetivoEsp21: number,
   objetivoEsp22: number,
   objetivoEsp23: number,
   objetivoEsp24: number,
   objetivoEsp25: number,
   objetivoEsp26: number,
   objetivoEsp27: number,
   objetivoEsp28: number,
   objetivoEsp29: number,
   objetivoEsp30: number,
   objetivoEsp31: number,
   objetivoEsp32: number,
   objetivoEsp33: number,
   objetivoEsp34: number,
   objetivoEsp35: number
}

export class Kinesiologia{
	
	constructor(

    public paciente: any,
    public user: any,
    public fecha?: string,
    public estabilidadDesplazamiento?:estabilidadDesplazamiento,
    public coordinacionDinamica?: coordinacionDinamica,
    public conductasPsicomotoras?: conductasPsicomotoras,
    public alineacionPostural?: alineacionPostural,
    
    public _id?: string
		
	)
	{}
}